BEGIN;

##Permite que los procedimientos se puedan crear (REVISAR)
##SET GLOBAL log_bin_trust_function_creators = 1;

SET @OLD_STORAGE_ENGINE=@@STORAGE_ENGINE, STORAGE_ENGINE=InnoDB;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `dev`;
CREATE SCHEMA IF NOT EXISTS `dev` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `dev` ;
#DROP SCHEMA IF EXISTS `sg1`;
#CREATE SCHEMA IF NOT EXISTS `sg1` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
#USE `sg1` ;

