-- SET GLOBAL log_bin_trust_function_creators = 0;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET STORAGE_ENGINE=@OLD_STORAGE_ENGINE;

COMMIT;
